export enum ErrorCode {
  // 用户相关错误
  USR_VAL_MISSING_FIELDS = "USR-VAL-001",
  USR_VAL_INVALID_INPUT = "USR-VAL-002",
  USR_DATA_NOT_FOUND = "USR-DATA-001",
  USR_DATA_DUPLICATE = "USR-DATA-002",

  // 身份验证相关错误
  AUTH_VAL_SIGNATURE_INVALID = "AUTH-VAL-001",
  AUTH_VAL_TOKEN_EXPIRED = "AUTH-VAL-002",
  AUTH_VAL_TOKEN_INVALID = "AUTH-VAL-003",
  AUTH_AUTH_UNAUTHORIZED = "AUTH-AUTH-001",

  // 数据库相关错误
  DB_CONN_FAILED = "DB-SYS-001",
  DB_QUERY_FAILED = "DB-SYS-002",
  DB_DATA_CONFLICT = "DB-DATA-001",

  // 系统相关错误
  SYS_UNKNOWN = "SYS-SYS-001",
  SYS_INTERNAL_ERROR = "SYS-SYS-002",
  SYS_TIMEOUT = "SYS-SYS-003",

  // 外部 API 错误
  API_VAL_RESPONSE_INVALID = "API-VAL-001",
  API_CONN_FAILED = "API-SYS-001",
  API_RATE_LIMIT_EXCEEDED = "API-SYS-002",
}
